{{- if .Values.cbNexusToken }}
{{- if .Values.cbNexusUsername }}
{{- $npmrc := printf "//nexus-internal.cloudbees.com/repository/npm-releases//:_authToken=%s:%s" .Values.cbNexusUsername .Values.cbNexusToken -}}
apiVersion: v1
data:
  file: {{ $npmrc | b64enc }}
kind: Secret
metadata:
  name: cb-npm-token
type: Opaque
{{- end }}
{{- end }}
