{{- if .Values.cbNexusToken }}
apiVersion: v1
data:
  file: {{ "//nexus-internal.cloudbees.com/repository/npm-releases//:_authToken=" | b64enc }}{{ (printf "%s:%s" .Values.cbNexusUser .Values.cbNexusToken) | b64enc }}
kind: Secret
metadata:
  name: npm-token
type: Opaque
{{- end }}