{{- if .Values.JenkinsXGitHub }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXGitHub.password | b64enc | quote }}
  username: {{ .Values.JenkinsXGitHub.username | b64enc | quote }}
kind: Secret
metadata:
  name: jx-pipeline-git-github-github
type: Opaque
{{- end }}