{{- if .Values.npmToken }}
{{- $npmrc := printf "//registry.npmjs.org/:_authToken=%s" .Values.npmToken -}}
apiVersion: v1
data:
  file: {{ $npmrc | b64enc }}
kind: Secret
metadata:
  name: npm-token
type: Opaque
{{- end }}