dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.32
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.465
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3793
- name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 1.5.2
# seems this chart setups up roles in kube-system namespace which we can't do via gitops and tillerless
# - name: cert-manager
#   repository: https://charts.jetstack.io
#   version: 0.7.0
