jenkins-x-platform:
  dockerRegistry: "gcr.io"
  PipelineSecrets:
    DockerConfig: |-
      {
          "credHelpers": {
              "gcr.io": "gcloud",
              "us.gcr.io": "gcloud",
              "eu.gcr.io": "gcloud",
              "asia.gcr.io": "gcloud",
              "staging-k8s.gcr.io": "gcloud"
          }
      }
  chartmuseum:
    enabled: true
    env:
      open:
        AUTH_ANONYMOUS_GET: true
        DISABLE_API: false
        STORAGE: google
        STORAGE_GOOGLE_BUCKET: chartmuseum.jenkins-x.io
        STORAGE_GOOGLE_PREFIX: charts
    gcp:
      secret:
        enabled: true
        key: gcs-chartmuseum.key.json
        name: gcs-jenkinsx-chartmuseum
    image:
      tag: v0.7.1

  controllerbuild:
    enabled: true
    env:
      JX_LOG_FORMAT: json
    image:
      repository: gcr.io/jenkinsxio/builder-go
      tag: 0.1.502

  jenkins:
    Agent:
      PodTemplates:
        Go:
          Containers:
            Go:
              Image: jenkinsxio/builder-go:latest
        Maven:
          Containers:
            Maven:
              Image: jenkinsxio/builder-maven:latest
          volumes:
          - mountPath: /root/.m2/
            secretName: jenkins-maven-settings
            type: Secret
          - mountPath: /home/jenkins/.docker
            secretName: jenkins-docker-cfg
            type: Secret
        Nodejs:
          Containers:
            Nodejs:
              Image: jenkinsxio/builder-nodejs:latest
  monocular:
    api:
      livenessProbe:
        initialDelaySeconds: 1000
  nexus:
    persistence:
      size: 100Gi
  postinstalljob:
    enabled: "true"

external-dns:
  sources:
  - ingress

  provider: google

  google:
    project: jenkins-x-infra
    serviceAccount: external-dns

  rbac:
    create: "true"

  domainFilters:
  - jrawlings.co.uk
  
datadog:
  datadog:
    logsEnabled: "true"
    logsConfigContainerCollectAll: "true"

featureFlagAPIKey: vault:gitOps/jenkins-x/environment-tekton-mole-dev/feature-flag-api-key:token-passthrough
npmToken: vault:gitOps/jenkins-x/environment-tekton-mole-dev/npm-token:token-passthrough
cbNexusToken: vault:gitOps/jenkins-x/environment-tekton-mole-dev/cb-nexus-token:token
cbNexusUsername: vault:gitOps/jenkins-x/environment-tekton-mole-dev/cb-nexus-token:username
codecovToken: vault:gitOps/jenkins-x/environment-tekton-mole-dev/codecov:token-passthrough
akmsToken: vault:gitOps/jenkins-x/environment-tekton-mole-dev/amazon-kms-id:token
JenkinsXDemoSA: vault:gitOps/jenkins-x/environment-tekton-mole-dev/jenkins-x-demo-sa:data

jx-app-prometheus:
  prometheus:
    nodeExporter:
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
    server:
      persistentVolume:
        size: 500Gi
